### ISSUE TITLE
Fails to compile in go1.11

### ISSUE THREAD

**Issue by gabbifish** [dedis/drand#70]
Current tip fails to compile with
```
github.com/dedis/drand/vendor/github.com/dedis/kyber/pairing/bn256.gfpMul: relocation target runtime.support_bmi2 not defined
```
Go 1.11 dropped support for support_bmi2, I believe. This is one example where we had to replace support_bmi2: https://github.com/cloudflare/bn256/issues/2 

I see that the group_info branch of dedis/kyber has already been fixed to use `HasBMI2`, but the vendored version of dedis/kyber in this directory uses an old version of group_info that uses `support_bmi2`. 

Problem is, when I run `dep ensure -upgrade` to get the latest version of `dedis/kyber` on branch `group_info`, I end up with the another error about a signature mismatch between the kyber library and drand's usage of it:

```
dkg/dkg.go:70:39: too many arguments in call to "github.com/dedis/drand/vendor/github.com/dedis/kyber/share/dkg/pedersen".NewDistKeyGenerator
	have ("github.com/dedis/drand/vendor/github.com/dedis/kyber/share/dkg/pedersen".Suite, kyber.Scalar, []kyber.Point, int, kyber.Scalar)
	want ("github.com/dedis/drand/vendor/github.com/dedis/kyber/share/dkg/pedersen".Suite, kyber.Scalar, []kyber.Point, int)

```

Is there a specific commit in the kyper group_info branch that works in go11.1 and is compatible with drand?

**Comment by gabbifish** [comment]
I realized that `dedis/kyber` now has generates randomness elsewhere and does not need to be provided as an argument to NewDistKeyGenerator. Submitted fix PR here: https://github.com/dedis/drand/pull/71

**Comment by gabbifish** [comment]
Fixed in #72
